apiVersion: apps/v1
kind: Deployment
metadata:
  name: ut-haushalt
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ut-haushalt
  template:
    metadata:
      labels:
        app: ut-haushalt
    spec:
      restartPolicy: Always
      imagePullSecrets:
      - name: private-registry-auth
      containers:
      - name: ut-haushalt
        image: registry.datexis.com/sero9164/urban-tech-bundeshaushalt
        ports:
        - containerPort: 8501
        env:
          - name: SOME_PATH
            value: placeholder
        command: ["streamlit", "run", "streamlit_app.py", "--server.port", "8501"]
        volumeMounts:
        - name: persistent-storage
          mountPath: /data
        readinessProbe:
          httpGet:
            path: /docs
            port: 8501
          initialDelaySeconds: 20
          periodSeconds: 10
          timeoutSeconds: 5 
        resources:
          requests:
            cpu: "50m"
          limits: 
            memory: "32Gi"
      volumes:
      - name: persistent-storage
        persistentVolumeClaim:
          claimName: ut-haushalt-pvc
